### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by DrMythical** [Phantom03167/Plants-vs.-Zombies-PVZ-Cheat#1]
按Home键没有反应

**Comment by Phantom03167** [comment]
> 按Home键没有反应

需要先点击“启动修改器”，切回游戏按Home键呼出界面

**Comment by DrMythical** [comment]
试过了，都点不出来

**Comment by Phantom03167** [comment]
> 试过了，都点不出来

你的游戏是Steam版吗？这个修改器我只针对steam版本进行编写，对其他版本无效(比如中文版)
exe和dll都需要下载，并要放到同一目录下

**Comment by DrMythical** [comment]
对啊，是Steam版的

**Comment by Phantom03167** [comment]
我这边测试是没有问题的。
你可以提供一些更具体详细的信息吗？
